workflow

diff --git a/.github/workflows/docker_up.yml b/.github/workflows/docker_up.yml
--- a/.github/workflows/docker_up.yml
+++ b/.github/workflows/docker_up.yml
@@ -8,5 +8,14 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Build the stack
-        run: docker-compose up 
+        run: docker-compose up -d
+      - name: Build Docker Image
+        run: |
+        if [[ $? -ne 0 ]] ; then
+echo "SQL query failed"
+    exit 1
+else
+    echo "SQL query success!"
+fi
+
    
